name: "email sender after workflow"

on:
    workflow_dispatch:

jobs:
    send_email:
        runs-on: ununtu-latest
        steps:
            - name: "checkout code"
              uses: action/checkout@v2

            - name: "setup python env"
              uses: action/setup-python@v2
              with:
                python-version: '3.x'
            
            - name: "Install dependencies"
              run: |
                python -m pip install --upgrade pip
                pip install smtplib email

            - name: "send email by python script"
              run: python mailer.py
              env: 
                WORKFLOW_NAME: ${{ github.workflow }}
                REPO_NAME: ${{ github.repository }}
                WORKFLOW_RUN_ID: ${{ github.run_id }}
                SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
                SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
                RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}